use bevy::prelude::*;
use crate::component;
use crate::system::{DamageType, Attack, Resistances, Reward};

#[derive(Asset, TypePath, Debug)]
pub struct Monster {
    pub name: String,
    pub sprite: String,
    pub health: i32,
    pub attack: Attack,
    pub armor: i32,
    pub resistances: Resistances,
    pub reward: Reward,
}

pub fn get_monster_details(index : i32) -> Monster {
    match index {
        0 => Monster {
            name: "Goblin".to_string(),
            sprite: "goblin.png".to_string(),
            health: 10,
            attack: Attack {
                damage: 5,
                damage_type: DamageType::Physical,
            },
            armor: 2,
            resistances: Resistances {
                physical: -5,
                magic: -10,
                fire: 0,
                ice: 0,
                poison: 0,
                lightning: 0,
                dark: 0,
                light: 0,
            },
            reward: Reward {
                name: "Tablet of Strength".to_string(),
                physical_resistance: 10,
                magic_resistance: 0,
                fire_resistance: 0,
                ice_resistance: 0,
                poison_resistance: 0,
                lightning_resistance: 0,
                dark_resistance: 0,
                light_resistance: 0,
                health: 10,
                damage: 5,
                armor: 2,
                damage_type: DamageType::Physical,
            },
        },
        1 => Monster {
            name: "Orc".to_string(),
            sprite: "orc.png".to_string(),
            health: 20,
            attack: Attack {
                damage: 10,
                damage_type: DamageType::Physical,
            },
            armor: 5,
            resistances: Resistances {
                physical: 0,
                magic: 0,
                fire: 0,
                ice: 0,
                poison: 0,
                lightning: 0,
                dark: 0,
                light: 0,
            },
            reward: Reward {
                name: "Ring of Fire".to_string(),
                physical_resistance: 0,
                magic_resistance: 0,
                fire_resistance: 10,
                ice_resistance: 0,
                poison_resistance: 0,
                lightning_resistance: 0,
                dark_resistance: 0,
                light_resistance: 0,
                health: 0,
                damage: 10,
                armor: 0,
                damage_type: DamageType::Fire,
            },
        },
        2 => Monster {
            name: "Troll".to_string(),
            sprite: "troll.png".to_string(),
            health: 30,
            attack: Attack {
                damage: 15,
                damage_type: DamageType::Physical,
            },
            armor: 10,
            resistances: Resistances {
                physical: 0,
                magic: 0,
                fire: 0,
                ice: 0,
                poison: 0,
                lightning: 0,
                dark: 0,
                light: 0,
            },
            reward: Reward {
                name: "Amulet of Ice".to_string(),
                physical_resistance: 0,
                magic_resistance: 0,
                fire_resistance: 0,
                ice_resistance: 20,
                poison_resistance: 0,
                lightning_resistance: 0,
                dark_resistance: 0,
                light_resistance: 0,
                health: 0,
                damage: 0,
                armor: 5,
                damage_type: DamageType::Ice,
            },

        },
        3 => Monster {
            name: "Dragon".to_string(),
            sprite: "dragon.png".to_string(),
            health: 50,
            attack: Attack {
                damage: 25,
                damage_type: DamageType::Fire,
            },
            armor: 15,
            resistances: Resistances {
                physical: 0,
                magic: 0,
                fire: 50,
                ice: 0,
                poison: 0,
                lightning: 0,
                dark: 0,
                light: 0,
            },
            reward: Reward {
                name: "Crown of Fire".to_string(),
                physical_resistance: 10,
                magic_resistance: 0,
                fire_resistance: 20,
                ice_resistance: 0,
                poison_resistance: 0,
                lightning_resistance: 0,
                dark_resistance: 0,
                light_resistance: 0,
                health: 0,
                damage: 25,
                armor: 10,
                damage_type: DamageType::Fire,
            },
        },
        4 => Monster {
            name: "Demon".to_string(),
            sprite: "demon.png".to_string(),
            health: 100,
            attack: Attack {
                damage: 50,
                damage_type: DamageType::Dark,
            },
            armor: 20,
            resistances: Resistances {
                physical: 0,
                magic: 0,
                fire: 0,
                ice: 0,
                poison: 0,
                lightning: 0,
                dark: 50,
                light: 0,
            },
            reward: Reward {
                name: "Cape of Darkness".to_string(),
                physical_resistance: 0,
                magic_resistance: 5,
                fire_resistance: 0,
                ice_resistance: 0,
                poison_resistance: 0,
                lightning_resistance: 0,
                dark_resistance: 20,
                light_resistance: 0,
                health: 20,
                damage: 0,
                armor: 15,
                damage_type: DamageType::Dark,
            },
        },
        5 => Monster {
            name: "Devil".to_string(),
            sprite: "devil.png".to_string(),
            health: 200,
            attack: Attack {
                damage: 100,
                damage_type: DamageType::Dark,
            },
            armor: 50,
            resistances: Resistances {
                physical: 0,
                magic: 0,
                fire: 0,
                ice: 0,
                poison: 0,
                lightning: 0,
                dark: 100,
                light: 0,
            },
            reward: Reward {
                name: "Sword of Darkness".to_string(),
                physical_resistance: 0,
                magic_resistance: 10,
                fire_resistance: 0,
                ice_resistance: 0,
                poison_resistance: 0,
                lightning_resistance: 0,
                dark_resistance: 30,
                light_resistance: 0,
                health: 30,
                damage: 50,
                armor: 20,
                damage_type: DamageType::Dark,
            },
        },
        6 => Monster {
            name: "FireElemental".to_string(),
            sprite: "fireelemental.png".to_string(),
            health: 500,
            attack: Attack {
                damage: 250,
                damage_type: DamageType::Fire,
            },
            armor: 100,
            resistances: Resistances {
                physical: 0,
                magic: 0,
                fire: 100,
                ice: 0,
                poison: 0,
                lightning: 0,
                dark: 0,
                light: 0,
            },
            reward: Reward {
                name: "Staff of Fire".to_string(),
                physical_resistance: 0,
                magic_resistance: 20,
                fire_resistance: 50,
                ice_resistance: 0,
                poison_resistance: 0,
                lightning_resistance: 0,
                dark_resistance: 0,
                light_resistance: 0,
                health: 50,
                damage: 100,
                armor: 50,
                damage_type: DamageType::Fire,
            },
        },
        _ => Monster {
            name: "Goblin".to_string(),
            sprite: "goblin.png".to_string(),
            health: 10,
            attack: Attack {
                damage: 5,
                damage_type: DamageType::Physical,
            },
            armor: 2,
            resistances: Resistances {
                physical: -5,
                magic: -10,
                fire: 0,
                ice: 0,
                poison: 0,
                lightning: 0,
                dark: 0,
                light: 0,
            },
            reward: Reward {
                name: "Tablet of Strength".to_string(),
                physical_resistance: 10,
                magic_resistance: 0,
                fire_resistance: 0,
                ice_resistance: 0,
                poison_resistance: 0,
                lightning_resistance: 0,
                dark_resistance: 0,
                light_resistance: 0,
                health: 10,
                damage: 5,
                armor: 2,
                damage_type: DamageType::Physical,
            },
        },
    }
}

pub fn load(
    mut commands: Commands,
    ) {
    commands.spawn(Camera2dBundle::default());
}

pub fn generate(
    mut commands: Commands,
    mut texture_atlases: ResMut<Assets<TextureAtlas>>,
    asset_server: Res<AssetServer>,
    ) {
    for i in 0..7 {
        let monster = get_monster_details(i);
        info!("Loading {:?}",monster.sprite);
        let texture_handle = asset_server.load(monster.sprite);
        let texture_atlas = TextureAtlas::from_grid(texture_handle, Vec2::new(256., 256.), 1, 1, None, None);
        let texture_atlas_handle = texture_atlases.add(texture_atlas);

        let id = commands.spawn(SpriteSheetBundle {
            texture_atlas: texture_atlas_handle,
            sprite: TextureAtlasSprite::new(0),
            transform: Transform::from_xyz(0., 0., 1.),
            visibility: Visibility::Hidden,
            ..default()
            }).id();
        
        commands.entity(id).insert((
            component::Monster,
            component::Name { name: monster.name },
            component::Health { current: monster.health, max: monster.health },
            component::Attack {
                damage: monster.attack.damage,
                damage_type: monster.attack.damage_type,
            },
            component::Armor { amount: monster.armor },
            component::Resistance {
                physical: monster.resistances.physical,
                magic: monster.resistances.magic,
                fire: monster.resistances.fire,
                ice: monster.resistances.ice,
                poison: monster.resistances.poison,
                lightning: monster.resistances.lightning,
                dark: monster.resistances.dark,
                light: monster.resistances.light,
            },
            component::Reward {
                name: monster.reward.name,
                physical_resistance: monster.reward.physical_resistance,
                magic_resistance: monster.reward.magic_resistance,
                fire_resistance: monster.reward.fire_resistance,
                ice_resistance: monster.reward.ice_resistance,
                poison_resistance: monster.reward.poison_resistance,
                lightning_resistance: monster.reward.lightning_resistance,
                dark_resistance: monster.reward.dark_resistance,
                light_resistance: monster.reward.light_resistance,
                health: monster.reward.health,
                damage: monster.reward.damage,
                armor: monster.reward.armor,
                damage_type: monster.reward.damage_type,
            },
            component::Floor { current: i },
        ));
    }
}

