use crate::system::combat::DamageType;
use std::fmt;

pub const REWARD_COUNT: i32 = 30;

#[derive(Debug)]
pub struct Reward {
    pub name: String,
    pub magic_resistance: i32,
    pub fire_resistance: i32,
    pub ice_resistance: i32,
    pub poison_resistance: i32,
    pub lightning_resistance: i32,
    pub dark_resistance: i32,
    pub light_resistance: i32,
    pub health: i32,
    pub damage: i32,
    pub armor: i32,
    pub damage_type: DamageType,
}

impl fmt::Display for Reward {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        let mut output_string = String::new();
        output_string.push_str(&format!("{}\n", self.name));
        if self.health != 0 {
            output_string.push_str(&format!(" Health: {:>+}\n", self.health));
        }
        if self.damage != 0 {
            output_string.push_str(&format!(" Damage: {:>+}\n", self.damage));
        }
        if self.damage_type != DamageType::Ignore {
            output_string.push_str(&format!(" Damage Type: {}\n", self.damage_type));
        }
        if self.armor != 0 {
            output_string.push_str(&format!(" Armor: {:>+}\n", self.armor));
        }
        if self.magic_resistance != 0 {
            output_string.push_str(&format!(" Magic Resistance: {:>+}\n", self.magic_resistance));
        }
        if self.fire_resistance != 0 {
            output_string.push_str(&format!(" Fire Resistance: {:>+}\n", self.fire_resistance));
        }
        if self.ice_resistance != 0 {
            output_string.push_str(&format!(" Ice Resistance: {:>+}\n", self.ice_resistance));
        }
        if self.poison_resistance != 0 {
            output_string.push_str(&format!(" Poison Resistance: {:>+}\n", self.poison_resistance));
        }
        if self.lightning_resistance != 0 {
            output_string.push_str(&format!(" Lightning Resistance: {:>+}\n", self.lightning_resistance));
        }
        if self.dark_resistance != 0 {
            output_string.push_str(&format!(" Dark Resistance: {:>+}\n", self.dark_resistance));
        }
        if self.light_resistance != 0 {
            output_string.push_str(&format!(" Light Resistance: {:>+}\n", self.light_resistance));
        }
        write!(f, "{}", output_string)
    }
}


pub fn get_reward(index: i32) -> Reward {
    match index {
        0 => Reward {
            name: "Gift of Strength".to_string(),
            magic_resistance: 0,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 0,
            light_resistance: 0,
            health: 10,
            damage: 10,
            armor: 5,
            damage_type: DamageType::Physical,
        },
        1 => Reward {
            name: "Wisdom and Knowledge".to_string(),
            magic_resistance: 5,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 0,
            light_resistance: 0,
            health: 0,
            damage: 0,
            armor: 0,
            damage_type: DamageType::Ignore,
        },
        2 => Reward {
            name: "Divine Protection".to_string(),
            magic_resistance: 0,
            fire_resistance: 10,
            ice_resistance: 0,
            poison_resistance: 10,
            lightning_resistance: 0,
            dark_resistance: 10,
            light_resistance: 0,
            health: 0,
            damage: 0,
            armor: 5,
            damage_type: DamageType::Ignore,
        },
        3 => Reward {
            name: "Favor of the Gods".to_string(),
            magic_resistance: 0,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 0,
            light_resistance: 0,
            health: 10,
            damage: 5,
            armor: 5,
            damage_type: DamageType::Light,
        },
        4 => Reward {
            name: "Protection".to_string(),
            magic_resistance: 1,
            fire_resistance: 1,
            ice_resistance: 1,
            poison_resistance: 1,
            lightning_resistance: 1,
            dark_resistance: 1,
            light_resistance: 1,
            health: 10,
            damage: 0,
            armor: 10,
            damage_type: DamageType::Ignore,
        },
        5 => Reward {
            name: "Sword of Flames".to_string(),
            magic_resistance: 0,
            fire_resistance: 10,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 0,
            light_resistance: 0,
            health: 0,
            damage: 10,
            armor: 0,
            damage_type: DamageType::Fire,
        },
        6 => Reward {
            name: "Shield of Force".to_string(),
            magic_resistance: 10,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 0,
            light_resistance: 0,
            health: 0,
            damage: 0,
            armor: 10,
            damage_type: DamageType::Ignore,
        },
        7 => Reward {
            name: "Bow of Lightning".to_string(),
            magic_resistance: 0,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: 10,
            dark_resistance: 0,
            light_resistance: 0,
            health: 0,
            damage: 10,
            armor: 0,
            damage_type: DamageType::Lightning,
        },
        8 => Reward {
            name: "Amulet of Protection".to_string(),
            magic_resistance: 0,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 5,
            light_resistance: 5,
            health: 10,
            damage: 0,
            armor: 5,
            damage_type: DamageType::Ignore,
        },
        9 => Reward {
            name: "Staff of the Elements".to_string(),
            magic_resistance: 0,
            fire_resistance: 5,
            ice_resistance: 5,
            poison_resistance: 0,
            lightning_resistance: 5,
            dark_resistance: 0,
            light_resistance: 0,
            health: 0,
            damage: 5,
            armor: 0,
            damage_type: DamageType::Magic,
        },
        10 => Reward {
            name: "Dagger of Venom".to_string(),
            magic_resistance: 0,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 10,
            lightning_resistance: 0,
            dark_resistance: 0,
            light_resistance: 0,
            health: 0,
            damage: 15,
            armor: 0,
            damage_type: DamageType::Poison,
        },
        11 => Reward {
            name: "Gloves of Power".to_string(),
            magic_resistance: 0,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 0,
            light_resistance: 0,
            health: 0,
            damage: 20,
            armor: 0,
            damage_type: DamageType::Physical,
        },
        12 => Reward {
            name: "Ring of Warding".to_string(),
            magic_resistance: 1,
            fire_resistance: 1,
            ice_resistance: 1,
            poison_resistance: 1,
            lightning_resistance: 1,
            dark_resistance: 1,
            light_resistance: 1,
            health: 1,
            damage: 0,
            armor: 0,
            damage_type: DamageType::Ignore,
        },
        13 => Reward {
            name: "Charm of Absorption".to_string(),
            magic_resistance: 2,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 0,
            light_resistance: 0,
            health: 0,
            damage: 0,
            armor: 2,
            damage_type: DamageType::Ignore,
        },
        14 => Reward {
            name: "Defenders Shield".to_string(),
            magic_resistance: 0,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 0,
            light_resistance: 0,
            health: 0,
            damage: 0,
            armor: 10,
            damage_type: DamageType::Ignore,
        },
        15 => Reward {
            name: "Scroll of Ice Blast".to_string(),
            magic_resistance: 0,
            fire_resistance: 0,
            ice_resistance: 10,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 0,
            light_resistance: 0,
            health: 0,
            damage: 10,
            armor: 0,
            damage_type: DamageType::Ice,
        },
        16 => Reward {
            name: "Tablet of Light".to_string(),
            magic_resistance: 0,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 0,
            light_resistance: 10,
            health: 0,
            damage: 10,
            armor: 0,
            damage_type: DamageType::Light,
        },
        17 => Reward {
            name: "Scepter of Darkness".to_string(),
            magic_resistance: 0,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 10,
            light_resistance: 0,
            health: 0,
            damage: 10,
            armor: 0,
            damage_type: DamageType::Dark,
        },
        18 => Reward {
            name: "Potion of Elemental Resistance".to_string(),
            magic_resistance: 0,
            fire_resistance: 2,
            ice_resistance: 2,
            poison_resistance: 0,
            lightning_resistance: 2,
            dark_resistance: 0,
            light_resistance: 0,
            health: 0,
            damage: 0,
            armor: 0,
            damage_type: DamageType::Ignore,
        },
        19 => Reward {
            name: "Aegis Shield".to_string(),
            magic_resistance: 2,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 0,
            light_resistance: 0,
            health: 0,
            damage: 0,
            armor: 15,
            damage_type: DamageType::Ignore,
        },
        20 => Reward {
            name: "Boots of Strength".to_string(),
            magic_resistance: 0,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 0,
            light_resistance: 0,
            health: 10,
            damage: 5,
            armor: 5,
            damage_type: DamageType::Ignore,
        },
        21 => Reward {
            name: "Medallion of Vitality".to_string(),
            magic_resistance: 0,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 0,
            light_resistance: 0,
            health: 15,
            damage: 0,
            armor: 0,
            damage_type: DamageType::Ignore,
        },
        22 => Reward {
            name: "Armor of the Titan".to_string(),
            magic_resistance: 0,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 0,
            light_resistance: 0,
            health: 20,
            damage: 0,
            armor: 10,
            damage_type: DamageType::Physical,
        },
        23 => Reward {
            name: "Helm of the Berserker".to_string(),
            magic_resistance: 0,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 0,
            light_resistance: 0,
            health: 10,
            damage: 15,
            armor: 5,
            damage_type: DamageType::Physical,
        },
        24 => Reward {
            name: "Breastplate of the Lightbringer".to_string(),
            magic_resistance: 0,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 15,
            light_resistance: 0,
            health: 10,
            damage: 5,
            armor: 10,
            damage_type: DamageType::Light,
        },
        25 => Reward {
            name: "Flamecloak of the Inferno".to_string(),
            magic_resistance: 0,
            fire_resistance: 10,
            ice_resistance: -10,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 0,
            light_resistance: 0,
            health: 0,
            damage: 5,
            armor: 0,
            damage_type: DamageType::Fire,
        },
        26 => Reward {
            name: "Quicksilver Gauntlets".to_string(),
            magic_resistance: 0,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: -10,
            dark_resistance: 0,
            light_resistance: 0,
            health: 0,
            damage: 0,
            armor: 10,
            damage_type: DamageType::Lightning,
        },
        27 => Reward {
            name: "Stormcaller's Robe".to_string(),
            magic_resistance: 0,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: 10,
            dark_resistance: -10,
            light_resistance: 0,
            health: 10,
            damage: 5,
            armor: 5,
            damage_type: DamageType::Lightning,
        },
        28 => Reward {
            name: "Glacial Glaive".to_string(),
            magic_resistance: -5,
            fire_resistance: 0,
            ice_resistance: 15,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 0,
            light_resistance: 0,
            health: 0,
            damage: 20,
            armor: 0,
            damage_type: DamageType::Ice,
        },
        29 => Reward {
            name: "Acidic Armor".to_string(),
            magic_resistance: 0,
            fire_resistance: -10,
            ice_resistance: -10,
            poison_resistance: 5,
            lightning_resistance: 0,
            dark_resistance: 0,
            light_resistance: 0,
            health: 10,
            damage: 0,
            armor: 20,
            damage_type: DamageType::Poison,
        },
        _ => Reward {
            name: "Nothing".to_string(),
            magic_resistance: 0,
            fire_resistance: 0,
            ice_resistance: 0,
            poison_resistance: 0,
            lightning_resistance: 0,
            dark_resistance: 0,
            light_resistance: 0,
            health: 0,
            damage: 0,
            armor: 0,
            damage_type: DamageType::Ignore,
        },
    }
}
